[server]
headless = true
enableCORS = true
enableXsrfProtection = false
port = 8501
maxUploadSize = 200

[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#1f2937"